dataSourceFactory:
  driverClass: org.postgresql.Driver
  user: postgres
  url: jdbc:postgresql://localhost/cognitiveConnections
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MyService Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
server:
  rootPath: /wants/
