version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    entrypoint: dockerize -wait tcp://db:5432
    command: java -jar app/build/libs/TMTYApplication.jar server app/TMTYConfiguration/docker.yml
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=cognitiveConnections

