version: '2'
services:
  web:
    build: .
    ports:
      - "30213:30213"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    volumes:
      - ./infrastructure/docker_compose_entrypoint.sh:/opt/docker_compose_entrypoint.sh
    command: /opt/docker_compose_entrypoint.sh
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/db/10-init_db.sql:/docker-entrypoint-initdb.d/10-init.sql